# Generated by Django 2.2.5 on 2019-09-14 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_candidatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatura',
            name='vaga',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vagas.Vaga'),
            preserve_default=False,
        ),
    ]
